name: Deploy to Vercel
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  VERCEL_ORG_ID: SzaYVAp3d25PG9pxSoRekvR3
  VERCEL_PROJECT_ID: prj_LOyvzSrMHoXWSX7t6gnXvLImjUJx

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel
        run: |
          vercel deploy --prod \
            --token=BCAKlynghBaH6oNRIAH5fplL \
            --yes
